#include "lexico.h"

#define TOKEN_MAIS         "+"
#define TOKEN_MENOS        "-"
#define TOKEN_IGUAL        "="
#define TOKEN_MULT         "*"
#define TOKEN_DIV          "/"
#define TOKEN_LPAREN       "("
#define TOKEN_RPAREN       ")"
#define TOKEN_INT          "NUM_INT: "
#define TOKEN_FLOAT        "NUM_REAL: "
#define TOKEN_PONTOVIRGULA ";"
#define TOKEN_VIRGULA      ","
#define TOKEN_DOISPONTOS   ":"
#define TOKEN_PONTO        "."
#define TOKEN_MAIOR        ">"
#define TOKEN_MENOR        "<"
#define TOKEN_PROGRAM      "program"
#define TOKEN_VARIAVEL     "VARIAVEL"
#define TOKEN_BEGIN        "begin"
#define TOKEN_VAR          "var"
#define TOKEN_IF           "if"
#define TOKEN_ELSE         "else"
#define TOKEN_THEN         "then"
#define TOKEN_WHILE        "while"
#define TOKEN_DO           "do"
#define TOKEN_TRUE         "true"
#define TOKEN_FALSE        "false"
#define TOKEN_ABRECHAVE    "{"
#define TOKEN_FECHACHAVE   "}"
#define TOKEN_DOISPONTOIGUAL ":="
#define TOKEN_MAIORIGUAL     ">="
#define TOKEN_MENORIGUAL     "<="
#define TOKEN_INTEGER        "integer"
#define TOKEN_REAL           "real"
#define TOKEN_FIM
#define TOKEN_ERRO         "ERRO"
#define TOKEN_END          "END"

int main(){
    abrirarquivo();
}
